---
title: "Допглавы экономики II, январь-февраль 2022"
subtitle: "Занятие 2. Экономика джунглей (продолжение)"
author: "В. Н. Пырлик"
date: "24 января 2022"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, fadeIn

## Сегодня

0. Разминка

--

1. Равновесие - окончание

--

2. Парето-стабильные размещения

--

3. Парето-стабильность **vs** Парето-оптимальность
4. Парето-стабильность **vs** отношения силы

--

5. Последовательная диктатура и Парето-стабильность

--

6. Социальный планировщик

--

7. ДЗ

---
class: section, animated, zoomIn

## Концепция Парето-стабильности

### в экономике джунглей

---
class: section, animated, zoomIn

## Парето-стабильные размещения

---
class: animated, fadeIn
## Парето-доминирование

.rb[NB!] Мы по-прежнему в условиях стандартных Джунглей!

</br>

--

.bb[Определение]

Размещение $b$ Парето-доминирует размещение $a$, если $\forall i\in N$

$$a(i)\succeq^i b(i),$$

и $\exists i\in N:$

$$b(i) \succ^i a(i).$$

---
class: animated, fadeIn
## Парето-доминирование

.gb[Пример 1]

i|1|2|3|4|
-:|-:|-:|-:|-:|
 |B|B|A|B
 |C|D|B|C
 |D|A|C|A
 |A|C|D|D

</br>

  | | | | |
-:|-:|-:|-:|-:|
a:|D|A|C|B 
b:|?|?|?|?|

.bb[?] Постройте Парето-доминирующе размещение

---
class: animated, fadeIn
## Парето-стабильность

.bb[Определение]

Размещение называется Парето-стабильным, если не сущетсвует размещений, которые его Парето-доминируют.

--

.bb[?] В Примере 1, размещение $b$ Парето-стабильно?

---
class: animated, fadeIn
## Парето-стабильность: важные комментарии

### Парето-стабильность vs Парето-оптимальность

Парето-стабильность - это концепция равновесия.

--

### Парето-стабильность и отношения силы

Парето-стабильность никак не связана с отношениями силы, используется только структура общества.

--

### Парето-стабильность и множественное доминирование

Если размещение доминируется несколькими другими, котоыре не сравнимы между собой, то это не препятствует тому, что первое размещение все равно будет заменено. 

---
class: animated, fadeIn
## Последовательаня диктатура и Парето-Стабильность

.rb[NB!] При любом отношении силы в обществе, результат последовательной диктатуры Праето-стабилен.

--

.bb[?] Как это доказать?

--

</br>

.rb[NB!] Равновесие в любых Джунглях Парето-стабильно.

.bb[?] А это?

--

.bb[?] Какие свойства типичных Джунглей здесь критичны?

---
class: section, animated, zoomIn

## Социальный планировщик
### в экономике джунглей

---
class: animated, fadeIn
## Социальный планировщик

.bb[?] В чем может быть функция социального планировщика? Какой может быть механизм?

--

Социальный планировщик контролирует отношения силы в обществе.

--

</br>

.rb[NB!] Для любого общества и любого Парето-стабильного размещения в нем существует такое отношение силы, что это размещение является равновесием в соответствующих джунглях.

---
class: animated, fadeIn
## **Домашняя работа 1** (до 18:00-СПб, 29.01.2021)

*Часть 1* 

- Доказать, что последовательная диктатура приводит к равновесию в Джунглях
- Доказать единственность равновесия в Джунглях
- Задача 1а в OR, стр. 118

---
class: animated, fadeIn
## **Домашняя работа 1** (до 18:00-СПб, 29.01.2021)

*Часть 2*

- В условиях стандатного общества, покажите, что если $a$ - Парето-стабильное размещение, то

$$\exists i\in N: a(i)\succeq^ih,\;\forall h\in H/a(i).$$


- Задача 6 в OR, стр. 119. Достаточно словесного объяснения.

---
class: animated, fadeIn
## **Домашняя работа 1** (до 18:00-СПб, 29.01.2021)

*Дополнительно* (не на проверку): разобрать доказательство теоремы 8.5 (стр. 114-115)

---
class: section, animated, rotateIn

# Увидимся в следующий раз!

