---
title: "Допглавы экономики II, январь-февраль 2021"
subtitle: "Занятие 4. Экономика обмена (1)"
author: "В. Н. Пырлик"
date: "5 февраля 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: section, animated, zoomIn

## основной раздел нашего курса:

# Экономика обмена

---
class: animated, fadeIn

## Сегодня

1. $H$ **vs** $R^2_+$: рынок делимых частных благ

2. Экономика обмена: определение 

--

3. Цены и бюджет

4. Распределение благ

--

5. Индивидуальный выбор

--

6. ДЗ


---
class: animated, fadeIn

## $H$ **vs** $R^2_+$: рынок делимых частных благ

На рынке домов блага были неделимыми: каждый дом $h\in H$ мог быть потреблен только одним индивидом.

--

.rb[!] В **экономике обмена** мы рассматриваем бесконечно делимые блага в количествах из $R^2_+$. 

--

.rb[!] Блага остаются **частными**: доступный запас блага делится между индивидами, потребление какой-то части одним индивидом исключает возможность потребеления ее кем-то еще.

---
class: animated, fadeIn

## Экономика обмена: определение

.bb[Определение] **Экономика обмена** состоит из:

- конечного множества индивидов $N$;

--

- набора предпочтений $(\succeq^i)_{i\in N}$, где $\forall i\in N$ $\succeq^i$ - монотонные и непрерывные отношения предпочтений на $R^2_+$; 

--

- исходного распределения благ $e$:

$$e:N\to R^2_+,\;\text{при этом}\;\sum_{i\in N}e_k(i)>0,\;k=1,2.$$

--

.bb[?] монотонность и непрерывность $\succeq$

---
class: animated, fadeIn

## Цены и бюджет

.bb[Определение] **Система цен** (.rmk[aka] *цены*) - это неотрицательная и ненулевая пара $p=(p_1,p_2)$.

--

.bb[Определение] **Стоимость набора благ** $x=(x_1,x_2)$ при ценах $p$ - это $px \equiv p\cdot x\equiv p_1x_1+p_2x_2$.

--

.bb[Определение] **Бюджетное множество индивида** (.rmk[aka] *бюджет индивида*) $i$ при начальном распределении $e$ и ценах $p$ - это

$$B(p,e(i))=\{x\in R^2_+:\;px\le pe(i)\}$$
---
class: animated, fadeIn

## Цены: интерпретация

1. **Денежное выражение**. Хотя в модели отсутствует товар-деньги, стоимость набора благ можно рассматривать, как сумму денег, которую можно потартить на покупку дргих наборов благ, если их стоимость не превышает имеющуюся.

--

2. **Пропорции обмена**. Обмен в экономике происходит линейно, в постоянной пропорции (при неизменных ценах). Вне зависимости от объема обмениваемых товаров, единица первого блага обменивается на $\frac{p_1}{p_2}$ единиц второго блага. 

--

.bb[NB] В любом случае, $\forall\lambda>0$ система цен $p$ эквивалентна системе $\lambda p$.
---
class: animated, fadeIn

## Распределение благ

Относительно экономики джунглей или рынка домов аналогами назначения и размещения в экономике обмена являются *назначение* и *распределение*.

--

.bb[Определение] **Назначение** в экономике обмена - это

$$a:N\to R^2_+.$$

--

.bb[Определение] Назначение $a$ назвается **распределением благ** (.rmk[aka] *распределением*) в экономике обмена, если

$$\sum_{i\in N}a(i)=\sum_{i\in N}e(i).$$

---
class: animated, fadeIn

### Забегая вперёд...

Наша задача - подойти к понятию равновесия в экономике обмена и проанализировать его свойства.

--

.rb[!] Концептуально равновесие на рынке домов  не отличается от равновесия на рынке делимых частных благ.

--

.bb[?] Что представляет собой равновесие на рынке домов?

--

В экономике обмена равновесие имеет в точности ту же структуру - сочетание распределения благ и системы цен, при которых все потребители "удовлетворены" сложившимся распределением.

---
class: animated, fadeIn

## Индивидуальный выбор в экономике обмена

.bb[Определение] Набор благ $a(i)$ является оптимальным с точки зрения индивида $i\in N$ в экономике обмена и при ценах $p$, если

$$a(i)\in B(p,e(i)),$$
и

$$\nexists b\in B(p,e(i)):\;b\succ^i a(i).$$
--

.bb[?] Что мы можем сказать о стоимости оптимального выбора индивида в экономике обмена?

---
class: animated, flipInX

### .gb[Пример 1.] Индивидуальный выбор 1: товары-комплементы

.bb[?] Опишите свойства индивидуального оптимального выбора индивида с ненулевым начальным запасом благ в экономике обмена и при произвольных ценах, если блага являются для индивида *совершенными комплементами в пропорции 1:1*.

---
class: animated, flipInY

### .gb[Пример 2.] Индивидуальный выбор 2: товары-субституты

.bb[?] Опишите свойства индивидуального оптимального выбора индивида с ненулевым начальным запасом благ в экономике обмена и при произвольных ценах, если блага являются для индивида *совершенными субститутами в пропорции $\alpha$:1*, $\alpha<1$.

---
class: animated, flipInX

### .gb[Пример 3.] Индивидуальный выбор 3

В экономике обмена индивид имеет запас только первого блага, а цена этого блага равна 1. 

Предпочтения индивида заданы функцией полезности

$$u(x_1,x_2)=\begin{cases}x_2,\;\text{если}\;x_2<\frac{x_1}{2},\\\frac{x_1+x_2}{3},\;\text{если}\;\frac{x_1}{2}\le x_2\le 2x_1,\\x_1,\;\text{если}\;x_2>2x_1.\end{cases}$$

.bb[?] Опишите оптимальный выбор индивида в зависимости от цены второго блага.

.bb[?] Как изменится результат, если индивид располагает и запасом второго блага, а цена первого не обязательно равна 1?

---
class: animated, fadeIn
## **Домашняя работа 4** (до 21:00-СПб, 11.02.2021)

В условиях экономик $E_3$ и $E_4$ из задачи 1 вучебнике (стр. 152) опишите *только* индивидуальный выбор потребителей (каждого в отдельности) в зависимости от цен и при заданных начальных запасах. 

---
class: section, animated, zoomIn

### Спасибо

## До встречи через неделю