---
title: "Допглавы экономики II, январь-февраль 2021"
subtitle: "Занятие 5. Экономика обмена (2)"
author: "В. Н. Пырлик"
date: "12 февраля 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, hands, zoomIn

</br></br></br>

## Разминка

# Индивидуальный выбор

### [wooclap.com/JAN21PAN](https://wooclap.com/JAN21PAN)

---
class: animated, fadeIn
## На чем мы остановились? (1)

.bb[Определение] **Экономика обмена** состоит из:

- конечного множества индивидов $N$;

- набора предпочтений $(\succeq^i)_{i\in N}$, где $\forall i\in N$ $\succeq^i$ - монотонные и непрерывные отношения предпочтений на $R^2_+$; 

- исходного распределения благ $e$:

$$e:N\to R^2_+,\;\text{при этом}\;\sum_{i\in N}e_k(i)>0,\;k=1,2.$$

---
class: animated, fadeIn
## На чем мы остановились? (2)

.rmk[В экономике обмена равновесие имеет в точности ту же структуру - сочетание распределения благ и системы цен, при которых все потребители "удовлетворены" сложившимся распределением.]

.bb[Определение] Набор благ $a(i)$ является оптимальным с точки зрения индивида $i\in N$ в экономике обмена и при ценах $p$, если

$$a(i)\in B(p,e(i))\color{gray}{=\{x\in R^2_+:\;px\le pe(i)\}},$$
и

$$\nexists b\in B(p,e(i)):\;b\succ^i a(i).$$


---
class: animated, fadeIn
## Сегодня

1. Индивидуальный выбор (окончание примеров)

--

2. Равновесие в экономике обмена

3. Определение **vs** интерпретация

--

4. Равновесие: примеры

--

5. ДЗ


---
class: animated, fadeIn
## Равновесие в экономике обмена: определение

.bb[Определение] **Конкурентное равновесие** в экономике обмена - это сочетание $\langle p,a\rangle$ цен $p$ и назначения $a$ таких, что

- $\forall i\in N$ $a(i)$ является оптимальным выбором $i$ при ценах $p$, и

- $a$ является распределением.

--

.bb[Определение] Распределение $a$ называется **равновесным распределением**, если существуют цены $p$ такие, что $\langle p,a\rangle$ - равновесие.

--

.bb[?] Почему в определении равновесия не сказать сразу, что $a$ - это распределение, а не просто назначение?

---
class: animated, fadeIn
## Равновесие: некоторые свойства

1. Если $\langle p,a\rangle$ - равновесие, то $\forall\lambda>0$ $\langle \lambda p,a\rangle$ - тоже равновесие.
.right[.rmk[.bb[?] почему?]]

--

2. Вне зависимости от структуры экономики, равновесие определено. Но может не существовать.

--

3. Равновесие называется *конкурентным*. Подразумевается, что **каждый индивид воспринимает цены в экономике, как данные**, не может повлиять на них своими действиями. 



---
class: animated, fadeIn

### .gb[Пример 1] 

- Экономика состоит из двух потребителей, $N=\{1,2\}$

- Предпочтения потребителей одинаковы, $u_i(x_{1},x_2)=x_1x_2$

- Начальные запасы в экономике: $e(1)=(2,0)$, $e(2)=(0,4)$

--

.bb[?] Найти все равновесия в экономике обмена.

--

.right[.rmk[.rb[!] Т.е. найти **все равновесные распределения** и по системе цен к каждому.]]

--

.right[.rmk[.rb[!] Или показать, что равновесий нет:</br>т.е. любое распределение не является равновесным.]]

---
class: animated, flipInX

### .gb[Пример 2] 

- Экономика состоит из двух потребителей, $N=\{1,2\}$

- Предпочтения потребителей одинаковы, $u_i(x_{1},x_2)=x_1\color{red}{+}x_2$

- Начальные запасы в экономике: $e(1)=(1,0)$, $e(2)=(0,1)$

.bb[?] Найти все равновесия в экономике обмена.

---
class: animated, flipInY

### .gb[Пример 3] 

- Экономика состоит из двух потребителей, $N=\{1,2\}$

- Предпочтения потребителей одинаковы, $u_i(x_{1},x_2)=\color{red}{\min}(x_1,x_2)$

- Начальные запасы в экономике: $e(1)=(\color{red}{2},0)$, $e(2)=(0,1)$

.bb[?] Найти все равновесия в экономике обмена.

---
class: animated, fadeIn
## **Домашняя работа 5** (до 21:00-СПб, 18.02.2021)

1. Задача 1a-d (OR, pp.152-153)

2. Задача 2c  (OR, p.153)

3. Задача 4 (OR, p.154)

4. Задача 6 (OR, pp.154-155)

---
class: center, animated, zoomIn

</br></br></br>

## Спасибо

### До встречи через неделю