---
title: "Допглавы экономики II, январь-февраль 2021"
subtitle: "Занятие 3. Рынок: основы"
author: "В. Н. Пырлик"
date: "28 января 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, fadeIn

## Сегодня

1. Джунгли: подведение итогов

--

2. Рынок: введение
3. Рынок **vs** Джунгли

--

5. Первая модель рынка
6. Равновесие: существование, единственность, Парето-устойчивость

--

7. ДЗ

---
class: section, animated, zoomIn

# Рынок

## Введение в рыночную экономику

---
class: animated, fadeIn

## Рынок: модель

.rb[!] Рынок - возможная альтернатива джунглям. *Мы все еще рассматриваем общество из индивидов и домов*, **но не рассматриваем отношения силы**.

--

.bb[Определение] **Рынок** состоит из *общества* и *исходного размещения* $e$, которое показывает исходные права собственности на дома в обществе.

--

.rb[!] Наличие прав собственности позволяет рассматривать варианты обмена между индивидами

---
class: animated, fadeIn

## Рынок: обмен

.gb[Пример 1]

i|1|2|3|4|
-:|-:|-:|-:|-:|
 |B|A|A|A
 |C|B|C|D
 |D|C|D|B
 |A|D|B|C

</br>

  | | | | |
-:|-:|-:|-:|-:|
e:|A|B|C|D 

.bb[?] Какие варианты обмена имеют смысл?

---
class: animated, fadeIn

## Рынок: обмен

.gb[Пример 2]

i|1|2|3|4|
-:|-:|-:|-:|-:|
 |D|A|A|B
 |C|D|C|C
 |A|C|D|D
 |B|B|B|A

</br>

  | | | | |
-:|-:|-:|-:|-:|
e:|A|B|C|D 

.bb[?] Найдите несколько вариантов обмена


---
class: animated, fadeIn

## Рыночное равновесие: цены

Чтобы перейти к концепции рыночного равновесия, каждому дому нужно сопоставить некоторую "ценность" (стоимость, цену). Индивид может позволить себе обменять свой дом на другой, который стоит не больше.

--

.bb[Определение] Система цен (*aka* цены) в экономике - это функция

$$p:H\to R.$$

---
class: animated, fadeIn

## Рыночное равновесие: индвивидуальный выбор

В рыночной экономике каждый индивид стремится наилучшим образом удовлетворить свои потребности, исходя из своих возможностей.

--

.bb[Определение] В экономике с ценами $p$ и исходным размещением $e$ дом $h^*\in H$ является выбором индивида $i\in N$, если

$$h^*\succeq^i h,\;\forall h\in \{h\in H:\;p(h)\le p(e(i))\},$$
--

или

$$\{h^*\} = \{h\in H:\;p(h)\le p(e(i))\}.$$

---
class: animated, fadeIn

## Рыночное равновесие: определение

.bb[Определение] Комбинация цен и назначения $<p,a>$ является равновесием на рынке, если

--

- $a$ является размещением, 

--

- и $a(i)$ является выбором $i$ при ценах $p$ $\forall i\in N$.

---
class: animated, fadeIn

## Рыночное равновесие

.gb[Пример 3]

i|1|2|3|4|
-:|-:|-:|-:|-:|
 |D|A|A|B
 |C|D|C|C
 |A|C|D|D
 |B|B|B|A
e:|A|B|C|D 
a:|C|D|A|B 
b:|D|A|C|B 

.bb[?] Может ли $a$ образовать равновесие с какими-то ценами? А $b$?

---
class: animated, fadeIn

## Рыночное равновесие: свойства

.rb[!] На любом рынке существует равновесие

--

.rb[!] Равновесное размещение на рынке единственное

--

.rb[!] Равновесное размещение Парето-устойчиво

--

.rb[!] Если исходное размещение Парето-устойчиво, то оно же будет равновесным


---
class: animated, fadeIn
## **Домашняя работа 3** (до 21:00-СПб, 04.02.2021)

1) Задача 5 из учебника (стр. 135). Достаточно словесного объяснения.

2) Задача 2 из учебника (стр. 134). В идеаде регение должно быть формальным.

---
class: section, animated, zoomIn

### Спасибо

## До встречи через неделю